# -*- coding: utf-8 -*-
"""Customers_Segmentation_Project_Ezgi_Yurtsever.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1aMjjpFTaA1J5flHC1-O7txkJzbTh47

# WELCOME!

Welcome to "***Clustering (Customer Segmentation) Project***". This is the last medium project of ***Machine Learning*** course. 

At the end of this project, you will have performed ***Cluster Analysis*** with an ***Unsupervised Learning*** method.

---

In this project, customers are required to be segmented according to the purchasing history obtained from the membership cards of a big mall.

This project is less challenging than other projects. After getting to know the data set quickly, you are expected to perform ***Exploratory Data Analysis***. You should observe the distribution of customers according to different variables, also discover relationships and correlations between variables. Then you will spesify the different variables to use for cluster analysis.

Finally, you should clustered customers using the ***K-Means Clustering*** method, after that label the clusters.

- ***NOTE:*** *This project assumes that you already know the basics of coding in Python. You should also be familiar with the theory behind Cluster Analysis and scikit-learn module as well as Machine Learning before you begin.*

---
---

# #Tasks

Mentoring Prep. and self study#### 

#### 1. Import Libraries, Load Dataset, Exploring Data
- Import Libraries
- Load Dataset
- Explore Data

#### 2. Exploratory Data Analysis (EDA)


#### 3. Cluster Analysis

- Clustering based on Age and Spending Score

    *i. Create a new dataset with two variables of your choice*
    
    *ii. Determine optimal number of clusters*
    
    *iii. Apply K Means*
    
    *iv. Visualizing and Labeling All the Clusters*
    
    
- Clustering based on Annual Income and Spending Score

    *i. Create a new dataset with two variables of your choice*
    
    *ii. Determine optimal number of clusters*
    
    *iii. Apply K Means*
    
    *iv. Visualizing and Labeling All the Clusters*
    
    
- Hierarchical Clustering

    *i. Determine optimal number of clusters using Dendogram*

    *ii. Apply Agglomerative Clustering*

    *iii. Visualizing and Labeling All the Clusters* 

- Conclusion

---
---

## 1. Import Libraries, Load Dataset, Exploring Data

There is a big mall in a specific city that keeps information of its customers who subscribe to a membership card. In the membetrship card they provide following information : gender, age and annula income. The customers use this membership card to make all the purchases in the mall, so tha mall has the purchase history of all subscribed members and according to that they compute the spending score of all customers. You have to segment these customers based on the details given.

#### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
# %matplotlib inline

plt.rcParams["figure.figsize"] = (10,7)
import warnings
warnings.filterwarnings('ignore')
warnings.warn("this will not show")
pd.set_option('display.max_rows', 500)

"""#### Load Dataset"""

df = pd.read_csv("Mall_Customers.csv")
df.head()

"""#### Explore Data

You can rename columns to more usable, if you need.
"""

df.shape

df.info()

df.columns = ['CustomerID', 'Gender', 'Age', 'Annual Income', 'Spending Score']
df.head()

df.describe()

df.isnull().sum()

df = df.drop(['CustomerID'], axis=1)

df.head()

"""---
---

## 2. Exploratory Data Analysis (EDA)

After performing Cluster Analysis, you need to know the data well in order to label the observations correctly. Analyze frequency distributions of features, relationships and correlations between the independent variables and the dependent variable. It is recommended to apply data visualization techniques. Observing breakpoints helps you to internalize the data.
"""

sns.pairplot(df)

plt.figure(figsize=(8,6))
sns.countplot(x='Gender', data=df)
plt.title('Count Plot of Gender', fontsize=12)
plt.xlabel('Gender', fontsize=11)
plt.ylabel('Count', fontsize=11)
plt.show()

sns.scatterplot(df, x='Age', y='Annual Income',hue='Gender', palette = 'crest')
plt.title('Relationship between Age, Annual Income and Gender', fontsize=12)
plt.xlabel('Age', fontsize=11)
plt.ylabel('Annual Income', fontsize=11)
plt.show()

sns.scatterplot(df, x='Age', y='Spending Score',hue='Gender', palette = 'crest')
plt.title('Relationship between Age, Spending Score and Gender', fontsize=12)
plt.xlabel('Age', fontsize=11)
plt.ylabel('Spending Score', fontsize=11)
plt.show()

sns.scatterplot(df, x='Spending Score', y='Annual Income',hue='Gender', palette = 'crest')
plt.title('Relationship between Spending Score, Annual Income and Gender', fontsize=12)
plt.xlabel('Spending Score', fontsize=11)
plt.ylabel('Annual Income', fontsize=11)
plt.show()

plt.subplot(1,3,1)
sns.boxplot(data=df, x='Gender', y='Spending Score', palette='crest');

plt.subplot(1,3,2)
sns.boxplot(data=df, x='Gender', y='Annual Income', palette = 'crest');

plt.subplot(1,3,3)
sns.boxplot(data=df, x='Gender', y='Age', palette = 'crest');

plt.subplots_adjust(left=0.1,
                    bottom=0.1,
                    right=0.9,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
plt.show()

"""## 3. Cluster Analysis

The main purpose of this project is to perform [cluster analysis](https://en.wikipedia.org/wiki/Cluster_analysis#:~:text=Cluster%20analysis%20or%20clustering%20is,in%20other%20groups%20(clusters).) with the [K-Means](https://towardsdatascience.com/understanding-k-means-clustering-in-machine-learning-6a6e67336aa1) algorithm. 

You can perform many [cluster analysis](http://www.stat.columbia.edu/~madigan/W2025/notes/clustering.pdf) using different variables. If you use a maximum of two variables for each cluster analysis, you can identify cluster labels more clearly.

First, the K-Means algorithm expects you to determine the number of clusters (*n_clusters*). You can determine the optimal number of clusters for each cluster analysis in various ways. In this case, you are expected to use the [Elbow Method](https://en.wikipedia.org/wiki/Elbow_method_(clustering).

Finally, different information is obtained in each analysis. Therefore, different labeling should be done as a result of each cluster analysis. 

Labeling example: 

- **Normal Customers**  -- An Average consumer in terms of spending and Annual Income
- **Spender Customers** --  Annual Income is less but spending high, so can also be treated as potential target customer.
"""

from sklearn.cluster import KMeans

"""### Clustering based on Age and Spending Score

#### *i. Create a new dataset with two variables of your choice*
"""

x1=df[['Age','Spending Score']]
x1.head()

"""#### *ii. Determine optimal number of clusters*"""

ssd1 = []

K = range(2,10)

for k in K:
    model1 = KMeans(n_clusters =k, random_state=42)
    model1.fit(x1)
    ssd1.append(model1.inertia_)

plt.plot(K, ssd1, "bo--")
plt.xlabel("Different k values")
plt.ylabel("inertia-error") 
plt.title("elbow method")

ssd1

-pd.Series(ssd1).diff()

from yellowbrick.cluster import KElbowVisualizer

model_1 = KMeans(random_state=42)
visualizer = KElbowVisualizer(model_1, k=(2,9))

visualizer.fit(x1)       
visualizer.poof();

"""### Why silhouette_score is negative?

![image.png](attachment:image.png)

silhouette_score = (b-a)/max(a,b)

b : the mean nearest-cluster distance 
a : the mean intra-cluster distance 

for red point, 

b = 1 
a = ((1+1)**0.5 + (1+1)**0.5)/2  ==> 1.41

silhouette_score = (1-1.41)/1.41 ==> -0.29
"""

from sklearn.metrics import silhouette_score

range_n_clusters = range(2,9)
for num_clusters in range_n_clusters:
    # intialise kmeans
    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
    kmeans.fit(x1)
    cluster_labels = kmeans.labels_
    # silhouette score
    silhouette_avg = silhouette_score(x1, cluster_labels)
    print(f"For n_clusters={num_clusters}, the silhouette score is {silhouette_avg}")

# The best score is n=4 cluster and also optimal point according to elbow is 4. 
#So, I choose the k = 4

from yellowbrick.cluster import SilhouetteVisualizer

model1 = KMeans(n_clusters=4, random_state=42)        
visualizer = SilhouetteVisualizer(model1)

visualizer.fit(x1)   
visualizer.poof();

"""#### *iii. Apply K Means*"""

K_means_model1 = KMeans(n_clusters=4, random_state=42)
K_means_model1.fit(x1)
labels1= K_means_model1.labels_
centroids1=K_means_model1.cluster_centers_

"""#### *iv. Visualizing and Labeling All the Clusters*"""

plt.figure(figsize=(12,6))
sns.set_style('white')
plt.scatter(x=df['Age'], y=df['Spending Score'],c=labels1,cmap='viridis')
plt.scatter(x = centroids1[: , 0] , y =  centroids1[: , 1], s = 300 , c = 'purple')
plt.xlabel('Age',fontsize=15)
plt.ylabel('Spending Score',fontsize=15)
plt.title('Customer Segmentation Based on Age and Spending Score',fontsize=18)
plt.show()

"""### Clustering based on Annual Income and Spending Score

#### *i. Create a new dataset with two variables of your choice*
"""

x2=df[['Annual Income','Spending Score']]
x2.head()

"""#### *ii. Determine optimal number of clusters*"""

# Elbow

ssd2 = []

K = range(2,10)

for k in K:
    model2 = KMeans(n_clusters =k, random_state=42)
    model2.fit(x2)
    ssd2.append(model2.inertia_)

plt.plot(K, ssd2, "bo--")
plt.xlabel("Different k values")
plt.ylabel("inertia-error") 
plt.title("elbow method")

ssd2

-pd.Series(ssd2).diff()

from yellowbrick.cluster import KElbowVisualizer

model_2 = KMeans(random_state=42)
visualizer = KElbowVisualizer(model_2, k=(2,9))

visualizer.fit(x2)       
visualizer.poof();

#Silhouette

range_n_clusters = range(2,9)
for num_clusters in range_n_clusters:
    # intialise kmeans
    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
    kmeans.fit(x2)
    cluster_labels = kmeans.labels_
    # silhouette score
    silhouette_avg = silhouette_score(x2, cluster_labels)
    print(f"For n_clusters={num_clusters}, the silhouette score is {silhouette_avg}")

# Max slhouette score for k = 5 and also elbow offer k = 5. I choosed the k=5

from yellowbrick.cluster import SilhouetteVisualizer

model2 = KMeans(n_clusters=4, random_state=42)        
visualizer = SilhouetteVisualizer(model2)

visualizer.fit(x2)   
visualizer.poof();

"""#### *iii. Apply K Means*"""

K_means_model2 = KMeans(n_clusters=5, random_state=42)
K_means_model2.fit(x2)
labels2= K_means_model2.labels_
centroids2=K_means_model2.cluster_centers_

"""#### *iv. Visualizing and Labeling All the Clusters*"""

plt.figure(figsize=(12,6))
sns.set_style('white')
plt.scatter(x=df['Annual Income'], y=df['Spending Score'],c=labels2,cmap='viridis')
plt.scatter(x = centroids2[: , 0] , y =  centroids2[: , 1], s = 300 , c = 'purple')
plt.xlabel('Annual Income',fontsize=15)
plt.ylabel('Spending Score',fontsize=15)
plt.title('Customer Segmentation Based on Annual Income and Spending Score',fontsize=18)
plt.show()

"""### Hierarchical Clustering

### *i. Determine optimal number of clusters using Dendogram*

### Clustering based on Age and Spending Score- x1
"""

from scipy.cluster.hierarchy import dendrogram, linkage

hc_ward = linkage(y = x1, method = "ward")
hc_complete = linkage(x1, "complete")
hc_average = linkage(x1, "average")
hc_single = linkage(x1, "single")

plt.figure(figsize = (20,8))
plt.title("Dendrogram")
plt.xlabel("Observations")
plt.ylabel("Distance")
dendrogram(hc_ward, leaf_font_size = 10);

"""## Clustering based on Annual Income and Spending Score- x2"""

hc_ward2 = linkage(y = x2, method = "ward")
hc_complete2 = linkage(x2, "complete")
hc_average2 = linkage(x2, "average")
hc_single2 = linkage(x2, "single")

plt.figure(figsize = (20,8))
plt.title("Dendrogram")
plt.xlabel("Observations")
plt.ylabel("Distance")
dendrogram(hc_ward2, leaf_font_size = 10);

"""### ii. *Apply Agglomerative Clustering*

#### Age and Spending Score- x1
"""



"""#### Annual Income and Spending Score- x2"""



"""### iii. *Visualizing and Labeling All the Clusters*

#### Age and Spending Score- x1
"""



"""#### Annual Income and Spending Score- x2"""



"""#### Interpretation based on Age and Spending Score- x1"""



"""### Conclusion

**cluster 0** : The average age is around 55, both annula_income and spending_scores are on average. 
It should be researched what can be done to direct to more spending.

**cluster 1**: The average age is around 45, the annula_income is high but the spending_scores are very low. 
This group is our target audience and specific strategies should be developed to drive this group to spend.

**cluster 2** :The average age is around 30. The annula_income is high and spending_scores are very high. 
This group consists of our loyal customers. Our company derives the main profit from this group. Very 
special promotions can be made in order not to miss it.    
    
**cluster 3**: The average age is around 25.both annula_income and spending_scores are on average. 
It should be researched what can be done to direct to more spending.

#### Interpretation based on Annual Income and Spending Score- x2
"""



"""## Conclusion

### Female

**cluster 0** : The average age is around 40, both annula_income and spending_scores are on average. 
It should be researched what can be done to direct more spending.

**cluster 1**: The average age is around 45, the annula_income is very high but the spending_scores is low.
This group is our target audience and special strategies need to be developed for this group.    

**cluster 2** :The average age is around 45. Both annula_income and spending_scores are low. It can be 
directed to shopping with gift certificates.

**cluster 3**: The average age is around 25. Low annual_incomes but very high spending scores. This 
group does a lot of shopping, but they do not bring much profit.

**cluster 4**: The average age is around 30, the annual income and the spending_score
is very high. This group consists of our loyal customers. Our company derives the main profit from this group. 
Very special promotions can be made in order not to miss it.

### Male

**cluster 0** : The average age is around 45, both annula_income and spending_scores are on average. 
It should be researched what can be done to direct more spending.

**cluster 1**: The average age is around 40, the annula_income is very high but the spending_scores is very low.
This group is our target audience and special strategies need to be developed for this group.    

**cluster 2** :The average age is around 50. Both annula_income and spending_scores are low. It can be 
directed to shopping with gift certificates.

**cluster 3**: The average age is around 25. Low annual_incomes but very high spending scores. This 
group does a lot of shopping, but they do not bring much profit.

**cluster 4**: The average age is around 30, the annual income and the spending_score
is very high. This group consists of our loyal customers. Our company derives the main profit from this group. 
Very special promotions can be made in order not to miss it.
"""



"""**cluster 0** : The average age is around 40, both annula_income and spending_scores are on average. 
It should be researched what can be done to direct more spending.

**cluster 1**: The average age is around 30, both annula_income and spending_scores are very high. 
This group consists of our loyal customers. Our company derives the main profit from this group. Very 
special promotions can be made in order not to miss it.

**cluster 2** :The average age is around 45. Both annula_income and spending_scores are low. It can be 
directed to shopping with gift certificates.

**cluster 3**: The average age is around 25. Low annual_incomes but very high spending scores. This 
group does a lot of shopping, but they do not bring much profit.

**cluster 4**: The average age is around 40, their annual income is very high but their spending_score
is very low. This group is our target audience and special strategies need to be developed for this 
group.
"""